number = int(input('Enter the number: '))
print(number % 2 == 0 and number % 4 == 0)

print(number < 7)
print(number > 5)
print(number <= 0)
print(number <= 0)
print(number == 3)
print(number != 0)
print(number < 33)
print(number > 4)
print(number <= 5)
print(number > 0)